import os

DEBUG = True
GITHUB_APP_ID=os.environ['GITHUB_APP_ID']
GITHUB_CLIENT_ID=os.environ['GITHUB_CLIENT_ID']
GITHUB_CLIENT_SECRET=os.environ['GITHUB_CLIENT_SECRET']
GITHUB_WEBHOOK_SECRET=os.environ['GITHUB_WEBHOOK_SECRET']
SECRET_KEY="supersecretkey"
GITHUB_PERSONAL_ACCESS_TOKEN=os.environ['GITHUB_PERSONAL_ACCESS_TOKEN']
GITHUB_PRIV_KEY_PATH = "/app/private-key.pem"
GITHUB_LIMIT_REQUEST = os.environ['GITHUB_LIMIT_REQUEST'] == 'True'

OPENREQ_BASEURL=os.environ['OPENREQ_BASEURL']

SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/integration-service/oris.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False

CELERY_BROKER_URL=os.environ['CELERY_BROKER_URL']

TRAINING_TIMEOUT = 1800
CLASSIFICATION_TIMEOUT = 1800
CONFIDENCE_TRESHOLD = 50